### ISSUE TITLE
Embedded blog links no longer exist

### ISSUE THREAD

**Issue by ruskintech** [okTurtles/wordpress-to-astro#1]
The blog post appears to no longer exist: 
https://blog.okturtles.org/2022/10/convert-wordpress-to-static-site/

**Comment by taoeffect** [comment]
Hi @ruskintech, you've found our repo for a blog post that hasn't been published yet! 😄 

Hopefully we'll have this out soon, my apologies for the delay.

**Comment by ruskintech** [comment]
Ha! How unlike me to show up early.

Wait a minute... this code's been up for two years!

**Comment by taoeffect** [comment]
Honestly I'm surprised myself 😅 

We wanted to release it after we released some other stuff, and that "other stuff" has been taking quite a long time.

**Comment by taoeffect** [comment]
Published!

https://blog.okturtles.org/2024/10/convert-wordpress-to-static-site/
